import turtle as t
t.tracer(200)
t.width(2)
t.bgcolor('black')
t.setup(1537,865)
color=('red','blue')
for i in range(1200):
       t.pencolor(color[i%2])
       t.fd(i)
       t.rt(120)
       t.fd(i)
       t.circle(i,30)
       t.fd(i)
       t.begin_fill()
       t.circle(i,120)
       t.fd(i)
       t.lt(30)
       t.end_fill()
       t.bk(i)
       t.lt(121)
t.done()
